# Generated by Django 4.2.27 on 2026-02-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_eventmatch_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='division',
            field=models.CharField(blank=True, choices=[('honors', 'Honors'), ('open', 'Open')], help_text='Division type for the event (Honors or Open)', max_length=20, null=True),
        ),
    ]
