# Generated by Django 6.0.1 on 2026-02-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0008_customevent_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='regentsleague_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
