# Generated by Django 6.0.1 on 2026-02-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_participant_regentsleague_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='regentsleague_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
